// <auto-generated />
namespace com.vorwardit.jollyapp.cms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigContent));
        
        string IMigrationMetadata.Id
        {
            get { return "201512310947492_MigContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
